kind: pipeline
type: docker
name: android nightly
trigger:
  branch:
    - dev
    - main
  event:
    - push
steps:
  - name: build android
    image: cirrusci/flutter:2.8.0
    commands:
      # Keep track of the time when build was started
      - echo $(date -Iseconds) > BUILD_START_TIME
      # Environment variables
      - export DEBIAN_FRONTEND=noninteractive
      - export ANDROID_NDK_HOME=/opt/android-sdk-linux/ndk-bundle/
      # Install dependencies (git should be pre-installed)
      - apt-get update && apt-get install --no-install-recommends -y cmake ninja-build
      - git submodule update --init --recursive
      - sdkmanager "ndk-bundle"
      # Set up flutter
      - flutter config --no-analytics
      - flutter pub get
      - flutter pub run build_runner build --delete-conflicting-outputs
      # Modify gradle build script (remove/change parts which don't work in this environment)
      - sed -i '/keystoreProperties\[/d' android/app/build.gradle
      - sed -i 's/version "3.10.2"/version "3.7.0+"/g' android/app/build.gradle
      - sed -i 's/signingConfig signingConfigs.release/signingConfig signingConfigs.debug/g' android/app/build.gradle
      # Modify package and app name to allow for installing alongside normal Syphon
      - sed -i 's/android:label="Syphon"/android:label="Syphon Nightly"/g' android/app/src/main/AndroidManifest.xml
      - sed -i 's/applicationId "org.tether.tether"/applicationId "org.syphon.syphon.nightly"/g' android/app/build.gradle
      # Modify the default ic_launcher to the nightly version
      - sed -i 's/ic_launcher_background">#34C7B5/ic_launcher_background">#161616/g' android/app/src/main/res/values/colors.xml
      # Build the APK
      - flutter build apk
      - cp build/app/outputs/flutter-apk/app-release.apk ./syphon.nightly.android.apk

  - name: release android
    image: golang:1.15
    environment:
      GITEA_SERVER_TOKEN:
        from_secret: GITEA_API_TOKEN
    commands:
      # Modify the existing release and add the android apk
      - go get code.gitea.io/tea
      - go install code.gitea.io/tea
      - tea login add -u https://git.syphon.org -n syphon
      - tea release create --tag "${DRONE_BRANCH}-$(echo $DRONE_COMMIT_SHA | cut -c1-7)-android" --target ${DRONE_COMMIT_SHA} --repo syphon-org/syphon --title "${DRONE_BRANCH}-nightly-android" --asset ./syphon.nightly.android.apk
---
kind: pipeline
type: docker
name: android branch build
trigger:
  branch:
    exclude:
      - dev
      - main
  event:
    - push
steps:
  - name: build android
    image: cirrusci/flutter:2.8.0
    commands:
      # Keep track of the time when build was started
      - echo $(date -Iseconds) > BUILD_START_TIME
      # Environment variables
      - export DEBIAN_FRONTEND=noninteractive
      - export ANDROID_NDK_HOME=/opt/android-sdk-linux/ndk-bundle/
      # Install dependencies (git should be pre-installed)
      - apt-get update && apt-get install --no-install-recommends -y cmake ninja-build
      - git submodule update --init --recursive
      - sdkmanager "ndk-bundle"
      # Set up flutter
      - flutter config --no-analytics
      - flutter pub get
      - flutter pub run build_runner build --delete-conflicting-outputs
      # Modify gradle build script (remove/change parts which don't work in this environment)
      - sed -i '/keystoreProperties\[/d' android/app/build.gradle
      - sed -i 's/version "3.10.2"/version "3.7.0+"/g' android/app/build.gradle
      - sed -i 's/signingConfig signingConfigs.release/signingConfig signingConfigs.debug/g' android/app/build.gradle
      # Modify package and app name to allow for installing alongside normal Syphon
      - sed -i 's/android:label="Syphon"/android:label="Syphon Nightly"/g' android/app/src/main/AndroidManifest.xml
      - sed -i 's/applicationId "org.tether.tether"/applicationId "org.syphon.syphon.nightly"/g' android/app/build.gradle
      # Modify the default ic_launcher to the nightly version
      - sed -i 's/ic_launcher_background">#34C7B5/ic_launcher_background">#161616/g' android/app/src/main/res/values/colors.xml
      # Build the APK
      - flutter build apk
      - cp build/app/outputs/flutter-apk/app-release.apk ./syphon.$(echo $DRONE_COMMIT_SHA | cut -c1-7).android.apk

  - name: release android
    image: golang:1.15
    environment:
      GITEA_SERVER_TOKEN:
        from_secret: GITEA_API_TOKEN
    commands:
      # Modify the existing release and add the android apk
      - go get code.gitea.io/tea
      - go install code.gitea.io/tea
      - tea login add -u https://git.syphon.org -n syphon
      - tea release create --tag "${DRONE_BRANCH}-$(echo $DRONE_COMMIT_SHA | cut -c1-7)-android" --target ${DRONE_COMMIT_SHA} --repo syphon-org/syphon --title "${DRONE_BRANCH}-$(echo $DRONE_COMMIT_SHA | cut -c1-7)-android" --asset ./syphon.$(echo $DRONE_COMMIT_SHA | cut -c1-7).android.apk
---
kind: pipeline
type: docker
name: linux nightly (amd64)
platform:
  os: linux
  arch: amd64
trigger:
  branch:
    - dev
    - main
  event:
    - push
steps:
  - name: build linux
    image: cirrusci/flutter:2.8.0
    commands:
      # Install dependencies
      - apt-get update -y
      - apt-get install -y cmake ninja-build clang pkg-config libgtk-3-dev liblzma-dev libblkid-dev libsecret-1-dev libolm-dev libolm3 libsqlite3-dev libjsoncpp-dev
      - git submodule update --init --recursive
      # Set up flutter config
      - flutter config --no-analytics
      - flutter pub get
      - flutter pub run build_runner build --delete-conflicting-outputs
      - flutter config --enable-linux-desktop
      # Build the linux app exec
      - flutter build linux --release
      - cp -a /usr/lib/x86_64-linux-gnu/libjsoncpp.so* build/linux/x64/release/bundle/lib/
      - tar -cvzf syphon.nightly.linux.x64.tar.gz -C build/linux/x64/release/bundle .

  - name: release linux
    image: golang:1.15
    environment:
      GITEA_SERVER_TOKEN:
        from_secret: GITEA_API_TOKEN
    commands:
      # Modify the existing release and add the android apk
      - go get code.gitea.io/tea
      - go install code.gitea.io/tea
      - tea login add -u https://git.syphon.org
      - tea release create --tag "${DRONE_BRANCH}-$(echo $DRONE_COMMIT_SHA | cut -c1-7)-linux" --target ${DRONE_COMMIT_SHA} --repo syphon-org/syphon --title "${DRONE_BRANCH}-nightly-linux" --asset ./syphon.nightly.linux.x64.tar.gz
---
kind: pipeline
type: docker
name: linux nightly (arm64)
platform:
  os: linux
  arch: arm64
trigger:
  branch:
    - dev
    - main
  event:
    - push
steps:
  - name: build linux
    image: cirrusci/flutter:2.8.0
    commands:
      # Install dependencies
      - apt-get update -y
      - apt-get install -y cmake ninja-build clang pkg-config libgtk-3-dev liblzma-dev libblkid-dev libsecret-1-dev libolm-dev libolm3 libsqlite3-dev libjsoncpp-dev
      - git submodule update --init --recursive
      # Set up flutter config
      - flutter config --no-analytics
      - flutter pub get
      - flutter pub run build_runner build --delete-conflicting-outputs
      - flutter config --enable-linux-desktop
      # Build the linux app exec
      - flutter build linux --release
      - cp -a /usr/lib/x86_64-linux-gnu/libjsoncpp.so* build/linux/x64/release/bundle/lib/
      - tar -cvzf syphon.nightly.linux.x64.tar.gz -C build/linux/x64/release/bundle .

  - name: release linux
    image: golang:1.15
    environment:
      GITEA_SERVER_TOKEN:
        from_secret: GITEA_API_TOKEN
    commands:
      # Modify the existing release and add the android apk
      - go get code.gitea.io/tea
      - go install code.gitea.io/tea
      - tea login add -u https://git.syphon.org
      - tea release create --tag "${DRONE_BRANCH}-$(echo $DRONE_COMMIT_SHA | cut -c1-7)-linux" --target ${DRONE_COMMIT_SHA} --repo syphon-org/syphon --title "${DRONE_BRANCH}-nightly-linux" --asset ./syphon.nightly.linux.x64.tar.gz
---
kind: pipeline
type: docker
name: linux branch build
platform:
  os: linux
  arch: amd64
trigger:
  branch:
    exclude:
      - dev
      - main
  event:
    - push
steps:
  - name: build linux
    image: cirrusci/flutter:2.8.0
    commands:
      # Install dependencies
      - apt-get update -y
      - apt-get install -y cmake ninja-build clang pkg-config libgtk-3-dev liblzma-dev libblkid-dev libsecret-1-dev libolm-dev libolm3 libsqlite3-dev libjsoncpp-dev
      - git submodule update --init --recursive
      # Set up flutter config
      - flutter config --no-analytics
      - flutter pub get
      - flutter pub run build_runner build --delete-conflicting-outputs
      - flutter config --enable-linux-desktop
      # Build the linux app exec
      - flutter build linux --release
      - cp -a /usr/lib/x86_64-linux-gnu/libjsoncpp.so* build/linux/x64/release/bundle/lib/
      - tar -cvzf syphon.$(echo $DRONE_COMMIT_SHA | cut -c1-7).linux.x64.tar.gz -C build/linux/x64/release/bundle .

  - name: release linux
    image: golang:1.15
    environment:
      GITEA_SERVER_TOKEN:
        from_secret: GITEA_API_TOKEN
    commands:
      # Modify the existing release and add the android apk
      - go get code.gitea.io/tea
      - go install code.gitea.io/tea
      - tea login add -u https://git.syphon.org
      - tea release create --tag "${DRONE_BRANCH}-$(echo $DRONE_COMMIT_SHA | cut -c1-7)-linux" --target ${DRONE_COMMIT_SHA} --repo syphon-org/syphon --title "${DRONE_BRANCH}-$(echo $DRONE_COMMIT_SHA | cut -c1-7)-linux" --asset ./syphon.$(echo $DRONE_COMMIT_SHA | cut -c1-7).linux.x64.tar.gz
# ---
# TODO: Remove to test Tea updates
# kind: pipeline
# type: docker
# name: test release
# trigger:
#   event:
#     - push
# steps:
#   - name: release test
#     image: golang:1.17
#     environment:
#       GITEA_SERVER_TOKEN:
#         from_secret: GITEA_API_TOKEN
#     commands:
#       - go install code.gitea.io/tea@latest
#       - tea --version
#       - which tea
#       - tea login add -u https://git.syphon.org
#       - tea release create --tag "${DRONE_BRANCH}-$(echo $DRONE_COMMIT_SHA | cut -c1-7)-linux" --target ${DRONE_COMMIT_SHA} --repo syphon-org/syphon --title "${DRONE_BRANCH}-$(echo $DRONE_COMMIT_SHA | cut -c1-7)-linux" --asset ./syphon.testing.linux.x64.tar.gz
# ---
